### ISSUE TITLE
Problems with debug mode

### ISSUE THREAD

**Issue by jpfeiffer16** [aaronduino/asciidots#12]
Hi again,

I'm not getting any output when I run a program in debug mode with -s.

Is this a known issue?

**Comment by aaronduino** [comment]
I've done this myself and gotten frustrated :)

It's part of the specifications:
> -s                Run without printing ANYTHING to the console. Useful for benchmarking

I added that flag so that I could benchmark my code after I rewrote it.

Side note: I just updated the online demo to [include debugging](https://asciidots.herokuapp.com/index.html?code=.-%24%22Hello%2C%20World!%22$%29)

Have fun with AsciiDots

**Comment by jpfeiffer16** [comment]
Lol. I just noticed that. Sorry about that. Going to try -d

**Comment by aaronduino** [comment]
No problem at all.

I'm going to close this issue.

**Comment by aaronduino** [comment]
Feel free to open issues at any time if you have any problems.
