### ISSUE TITLE
Interpreter change proposal: dots move at the same time

### ISSUE THREAD

**Issue by aaronduino** [aaronduino/asciidots#21]
Right now, as seen in the readme's GIF, only one dot moves at a time.

The proposal is to change that such that dots move in parallel (at the same time).

At the time being, this mode can be enabled with the (temporary) `-p` flag.

No test/sample programs are broken by enabling "parallel mode", and the only code that would be broken is code relying on interpreter quirks not specified in the readme's language/interpreter specs anyway.

What does everyone think about this?
Should "parallel mode" be implemented as default behaviour, or should the language be kept the same?

Either way, I think the `-p` flag should be dropped once the decision is made.

**Comment by ddorn** [comment]
I totally agree with this idea, it makes more sense to me to have all dots moving at the same time. In an electric circuit, electrons won't wait when they go back to the same place or when an other one is moving. Same for car races or light bouncing on mirrors.

I'm not anymore sure that it changes nothing to asciidots codes because if you do this change, the dot that arrives first somewhere won't be the most left/top/*something not really previsible* but the one with the shortest path.
I will try to find an example tomorrow !

**Comment by aaronduino** [comment]
This is the now the default

**Comment by Seanld** [comment]
Shall we close this issue, then?
