### ISSUE TITLE
EOF support

### ISSUE THREAD

**Issue by aaronduino** [aaronduino/asciidots#55]
Anybody have any ideas for good ways to let asciidots code detect EOF (end of file) input?

**Comment by ddorn** [comment]
You need to surround the call to each `input` with a `except EOFError` ;)

**Comment by aaronduino** [comment]
Since we plan to implement #53 with print-like modifier syntax (e.g. `#a?`), should the underscore (`_`) modifier enable some form "peek" reading, where ascii input is passively read?

This would allow numeric input code (i.e. `#?`) to handle EOF without consuming any numbers.

Here's a sample of how this would be used:
```
         .
         |
/--#?----<------\
|               |
*--$#-----------~--$"We got EOF"-&
|               |
\-#_a?-*----{!}-/
       \-#26-/ `` 26 is the ascii code for EOF
```

Here's a slightly code-golfed equivalent (to show that EOF checking wouldn't be _too_ bulky):
```
   .
/#?<-#$-~-$"We got EOF"-&
*#_a?{=}/
\#26--/
```

I'm open to any other ideas.

**Comment by JackDesBwa** [comment]
EOF is (always?) a tricky question.

First of all, I think there is a misconception somewhere in the last comment.
Ascii table has a lot of special meaning bytes at its beginning and most of them are rarely used nowadays.
However, none of them is EOF. Actually, EOF is not a character, it is the concept that there is no more to read.

Some API use a special value to return this information. For example, in C, getchar returns a int which is way bigger than the expected information (a byte) just because of this extra information that has to be different from all possible regular values. On 32bits architectures, it is a 4× waste at each reading except at the end of stream. Other API treat it as exceptional case, e.g. with exception mechanism or special functions to read the status. There might be other ways I don't think of now.

In asciidots, the 'special value' way is probably not an ideal choice since, without modifier, the input is not explicitly restricted in range -- i.e. no special value is special enough to endorse this role.

This comment does not lead to a pragmatic solution and is not very constructive ; but I think it could be useful to highlight some disadvantages of your proposition so that a better informed choice can be made.

**Comment by aaronduino** [comment]
Oh, good catch.

Tbh, I did in fact have the misconception that EOF was a character -- thanks for clarifying :)

Your also make a good point about not having special values from 0 to 255 since it fundamentally does not make sense.

If we do end up needing to have a "special value", it would need to be either below 0 or above 255 and that value would only be special when returned from ascii input chars (i.e. `#a?`)

A special value below zero seems more natural for a special meaning, but it is tedious to compare negative values in asciidots.

Should we go with a value like 256 for EOF?
Negative numbers?
Something completely different?

I'm open to any suggestions.
