### ISSUE TITLE
IndexError: pop from empty list

### ISSUE THREAD

**Issue by aaronduino** [aaronduino/asciidots#57]
This error message needs to be clarified.

See https://github.com/aaronduino/asciidots/issues/54#issuecomment-344757596

**Comment by aaronduino** [comment]
I think it would be good if a dot tries to figure out its return teleport location, but if it's ambiguous, an error should be thrown.

**Comment by ddorn** [comment]
I think that would be a terrible idea, or at least, useless. A library is not supposed to the context where it's called and is supposed to work in any context if it's used one, or fifty times and therefore a library writer cannot let an inner dot go outside because this would work if and only if the library is called once.

Plus, there is always a way to return a dot that is an input instead of an inner dot. 

However, changing the error message would be more appropriate, IMO.

**Comment by aaronduino** [comment]
I agree. I won't implement return inference.

I will improve the error message, tho.
