### ISSUE TITLE
Online demo is just displaying "Not Connected..."

### ISSUE THREAD

**Issue by dospunk** [aaronduino/asciidots#6]
Title says it all I think

**Comment by aaronduino** [comment]
The problem seems to be that the frontend server has loaded but the backend server is still booting up from [Heroku server sleep](https://devcenter.heroku.com/articles/free-dyno-hours#dyno-sleeping).

I am working on a fix that will make the frontend try to connect again after a short delay in an attempt to connect to the now-waking-up backend.

I have no idea why I have separate servers running the frontend and backend.
I hope to merge them soon.

**Comment by aaronduino** [comment]
I tried to make it automatically reconnect, but it ended up confusing the backend (the frontend dropped sockets while the backend held on).

I decided to just tell the user to wait and reload ([frontend commit b85e8665](https://github.com/aaronduino/asciidots-static-server/commit/b85e86658af56cea1876e6416bee79c68f802f36)).
This is not optimal, but its better than nothing.

Should I close this issue?

**Comment by aaronduino** [comment]
I am going to close for now.

If anyone figures out a good solution, feel free do a Pull Request.

**Comment by aaronduino** [comment]
Reopening, deciding to add to the project of improving the demo experience

**Comment by aaronduino** [comment]
There is definitely a problem with [the backend](https://github.com/aaronduino/asciidots-demo-backend).

So far, my only solution has been restarting the server every day. I am fairly sure that this would not be acceptable in a corporate environment.

**Comment by aaronduino** [comment]
I think that this problem can be fixed with #11 

It turns out that the debug text and ansi are making the program's output text so long that it is trimmed

**Comment by aaronduino** [comment]
This was fixed when the frontend was moved off of heroku.

I'm closing this, for the last time.
