### ISSUE TITLE
Error: dot cannot determine location (except for AsciidotsDebugger)

### ISSUE THREAD

**Issue by scottbeebiwan** [aaronduino/asciidots#63]
I previously explained this, but when I use `asciidots (file)` instead of `debugger.py (file)` from [the graphical debugger](https://github.com/ddorn/AsciidotsDebugger) which the online AsciiDots interpreter is based on, a file with teleportation in it only spits out `error: dot cannot determine location...`.
The program I made that throws this:
```
%$A %$B

.-#99--(--$_#--$' bottles of beer on the wall.'--$_#--$' bottles of beer,'--$'Take one down, pass it around...'--A
      B/

  /-#1-\           /#0-v---\             /-$'No more bottles of beer on the wall.'-&
  |    |           |   |   0        /----~-$_#--$' bottles of beer on the wall.'-$''-B
A-*---{-}\    /----*--[=]  # /------+----/
         |    |    |   \-*-/ |      ~-\
         \\   |    \-----+---+--*---+-/ 
          \---/          \---/  \-#1/
```

**Comment by ddorn** [comment]
It's very interesting that you don't get that error with my debugger, since this error is thrown by the interpreter, and AsciidotDebugger uses the same interpreter. I guess that's for another issue though (could you try re-installing the AsciidotsDebbuger, I pushed a commit to always use the pip installed version of the interpreter. You should get that error.).

Regarding your suggestions, @aaronduino, the second option is clearly a terrible idea, since quotes and asciidots are non-linear, it would mean escaping for the four directions? That's ugly.   
The first option would definitely break code, like your quine ` ($'.-#40-$_a#-#36-$_a#-#39-$_a#)` and again, remember that dots also go up and down and therefore the same dot can be used for a lot of different things at the same time, and to me, that's one of the reasons that makes AsciiDots so beautiful.

However, there's one fix that you can use, it's not the prettiest fix ever but... This error is thrown when a dot doesn't know where to go after spawning, so you can just create a way to go. You can just place a `|` over or  under the `.` so it would take this path and then just die because there's nothing after.

The other fix would be that we don't throw an error when a dot has nowhere to go, we just don't spawn it or kill it directly. I guess it must be a not-to-bad option: I don't see too much inconvenant yet.

**Comment by aaronduino** [comment]
Thanks for the insight, @ddorn

I do like your idea of dots simply dying if they don't have anywhere to go. This would relate to how they also dye when they go off of the end of a path (e.g. `.----`)

As far as I know, the only potential issue with this is that it could cause confusion. At the same time, I doubt that anyone would be confused for long once they take a look at the debugger.
